add-html-css-js-1
Avelinka/brain-waves-js-proj pull request #43
Opened 2023-10-14 16:52 UTC by VladcatUA

2023-10-14 20:55 UTC, Avelinka requested changes

2023-10-14 20:55 UTC, Avelinka commented on src/css/shopping-list.css
> +    font-family: DM Sans;
`font-family: 'DM Sans', sans-serif;` якщо вже треба, хоча в тебе на сторінці підключен основний файл із шрифтами, а там шрифт задан одразу на боді, тож не потрібен взагалі.

2023-10-14 20:55 UTC, Avelinka commented on src/css/shopping-list.css
> +.is-hidden {
```
.is-hidden {
  opacity: 0;
  visibility: hidden;
  pointer-events: none;
}
```
У нас у файлику ресет є стиль is-hidden, тож треба назву замінити

2023-10-14 20:55 UTC, Avelinka commented on src/css/shopping-list.css
> +    align-items: center;
24 та 26 рядки...

2023-10-14 20:55 UTC, Avelinka commented on src/css/shopping-list.css
> +    font-family: DM Sans;
Про `font-family` написала вище

2023-10-14 20:55 UTC, Avelinka commented on src/css/shopping-list.css
> +    font-family: DM Sans;
Ну ти зрозумів :)

2023-10-14 20:55 UTC, Avelinka commented on src/css/shopping-list.css
> +    font-family: DM Sans;
І тут

2023-10-14 20:55 UTC, Avelinka commented on src/css/shopping-list.css
> +    font-family: DM Sans;
І тут

2023-10-14 20:55 UTC, Avelinka commented on src/css/shopping-list.css
> +    .hidden {
До речі, 18-20 рядки твій клас, що потребує зміни назви, такий самий, то може просто використовувати цей клас `hidden` і там і тут?

2023-10-14 20:55 UTC, Avelinka commented on src/css/shopping-list.css
> +    .container {
```
.container {
  max-width: 375px;
  margin: 0 auto;
  padding: 0 20px;
}

@media screen and (min-width: 768px) {
  .container {
    max-width: 768px;
    padding-left: 32px;
    padding-right: 32px;
  }
}

@media screen and (min-width: 1440px) {
  .container {
    max-width: 1440px;
    padding-left: 24px;
    padding-right: 24px;
  }
}
```
Це наші базові стилі. Тож треба додати ще 1 клас, там де тобі потрібно паддінги змінити, і вже у додатковому класі міняти паддінги. Бо зараз твоє правило буде замінювати собою стиль для всього сайту, бо нижче по коду написано.

2023-10-14 20:55 UTC, Avelinka commented on src/css/shopping-list.css
> +@media screen and (min-width: 1440px) {
Те саме, що і на 50 рядку. Перезаписує стилі для всього сайту, чим ламає його. Зміни на додатковому класі паддінги

2023-10-14 20:55 UTC, Avelinka commented on src/css/shopping-list.css
> +    .hidden {
Хм, в тебе вище вже є клас `hidden`
```
.hidden {
    display: none;
}
```
Ти зараз його або перезаписав повністю, або до `display: none;` додав флекс та ширину з висотою... Ти точно саме цього хочеш? Може змінити назву класу?

2023-10-14 20:55 UTC, Avelinka commented on src/js/shopping-list.js
> +        hiddenElement.classList.remove('is-hidden');
Про класи написала. Поміркуй, що де, бо я вже заплуталась :) В принципі, базовий із-хіден також ховає елементи

2023-10-14 20:55 UTC, Avelinka commented on src/js/shopping-list.js
> +    messageElement.classList.remove('is-hidden');
І тут зверни увагу

2023-10-14 20:55 UTC, Avelinka commented on src/shopping-list.html
> +    <include src="./partials/fonds-ukraine.html"></include>
Так. У нас збірка на Vite, тож елементи підключаються по іншому
```
 <load ="./partials/header.html" />
 <load ="./partials/all-category.html" />
 <load ="./partials/fonds-ukraine.html" />
```

2023-10-14 20:55 UTC, Avelinka commented on src/css/shopping-list.css
> +    .support-ukraine {
Це у тебе в розмітці, чи у Артема? Якщо у Артема, то треба бути обережним з цим

2023-10-14 20:55 UTC, Avelinka commented on src/css/shopping-list.css
> +/*dark*/
Це вже під свічер лайт/дарк?

2023-10-14 23:12 UTC, VladcatUA commented on src/css/shopping-list.css
> +/*dark*/
Так)

2023-10-15 04:25 UTC, Avelinka approved these changes

2023-10-15 04:28 UTC, merged