Requests for fetch
Avelinka/brain-waves-js-proj pull request #6
Opened 2023-10-11 20:34 UTC by AnastasiiaKalashnikova

4 ф-ції для запиту на бек

2023-10-11 22:04 UTC, Avelinka commented on src/js/fetch-requests.js
> +        console.log(categoriesList)
9 пункт "Критеріїв допуску роботи:
9. Консоль розробника не видає помилок чи **console.log'ів.**
Повидаляй, будь-ласка, усі консоль-логі

2023-10-11 23:21 UTC, Avelinka commented on src/js/fetch-requests.js
> +        const categoriesList = await response.data
'axios.get' повертає об'єкт відповіді, тож ми можемо отримати дані, використовуючи response.data без await:
**const categoriesList = response.data;**
Також, я б спочатку зробила перевірку response.status, а потім оголосила би змінну categoriesList

2023-10-11 23:43 UTC, Avelinka commented on src/js/fetch-requests.js
> +        throw new Error(response)
В принципі все норм, але давай зробимо код більш зрозумілим і зручним для обробки помилок:
**throw new Error(`Request failed with status: ${response.status}`);**

2023-10-11 23:53 UTC, Avelinka commented on src/js/fetch-requests.js
> +        console.log (error)
Можемо замість console.log (error) використовувати бібліотеку Notiflix, яку ми все одно підключили. Наприклад:
Notiflix.Notify.failure('Error fetching category-list. Please try again later.');
І не забудь імпортувати Notiflix після axios :)
Також забула у кінці додати throw error;

2023-10-12 00:02 UTC, Avelinka commented on src/js/fetch-requests.js
> +    } catch {
catch **_(error)_**

2023-10-12 00:03 UTC, Avelinka commented on src/js/fetch-requests.js
> +    } catch {
catch **_(error)_**

2023-10-12 00:34 UTC, Avelinka requested changes

2023-10-12 00:34 UTC, Avelinka commented on src/js/fetch-requests.js
> +        const categoriesList = await response.data
Await у даному випадку необов'язкове:
**const categoriesList = response.data;**
Можна в усіх 4 функціях це змінити :)
Також, я б спочатку зробила перевірку response.status (так само, для всіх 4 функцій), і вже потім оголосила би змінну categoriesList

2023-10-12 00:34 UTC, Avelinka commented on src/js/fetch-requests.js
> +        throw new Error(response)
В принципі все норм, але давай зробимо код більш зрозумілим і зручним для обробки помилок:
**throw new Error(`Request failed with status: ${response.status}`);**
Можна в усіх 4 функціях це змінити :)

2023-10-12 00:34 UTC, Avelinka commented on src/js/fetch-requests.js
> +        console.log (error)
Можемо замість _console.log (error)_ використовувати бібліотеку Notiflix, яку ми все одно підключили. Наприклад:
**Notiflix.Notify.failure('Error fetching category-list. Please try again later.');**
І не забудь імпортувати Notiflix після axios :)
Також забула _у кінці додати_ **throw error;**
Так само, можна в усіх 4 функціях це змінити :)

2023-10-12 00:34 UTC, Avelinka commented on src/js/fetch-requests.js
> +    } catch {
catch **(error)**

2023-10-12 00:34 UTC, Avelinka commented on src/js/fetch-requests.js
> +    } catch {
catch **(error)**

2023-10-12 13:23 UTC, AnastasiiaKalashnikova commented on src/js/fetch-requests.js
> +    } catch {
done

2023-10-12 13:23 UTC, AnastasiiaKalashnikova commented on src/js/fetch-requests.js
> +    } catch {
done

2023-10-12 13:28 UTC, AnastasiiaKalashnikova commented on src/js/fetch-requests.js
> +        const categoriesList = await response.data
done

2023-10-12 13:47 UTC, AnastasiiaKalashnikova commented on src/js/fetch-requests.js
> +        throw new Error(response)
done

2023-10-12 14:06 UTC, AnastasiiaKalashnikova commented on src/js/fetch-requests.js
> +        console.log (error)
Бібліотеку використала.
А щодо throw error ... 
В кечі додати throw error? Не зовсім розумію навіщо...

2023-10-12 14:32 UTC, Avelinka approved these changes

2023-10-12 14:34 UTC, Avelinka approved these changes

2023-10-12 14:34 UTC, merged